echo "put 'italians', '1', 'personal-data:name',  'Paolo Sorrentino'"
echo "put 'italians', '1', 'personal-data:city',  'Verona'"
echo "put 'italians', '1', 'professional-data:role',  'Gestao Comercial'"
echo "put 'italians', '1', 'professional-data:salary',  '2394'"
echo "put 'italians', '2', 'personal-data:name',  'Domenico Barbieri'"
echo "put 'italians', '2', 'personal-data:city',  'Padua'"
echo "put 'italians', '2', 'professional-data:role',  'Psicopedagogia'"
echo "put 'italians', '2', 'professional-data:salary',  '11890'"
echo "put 'italians', '3', 'personal-data:name',  'Maria Parisi'"
echo "put 'italians', '3', 'personal-data:city',  'Taranto'"
echo "put 'italians', '3', 'professional-data:role',  'Optometria'"
echo "put 'italians', '3', 'professional-data:salary',  '20960'"
echo "put 'italians', '4', 'personal-data:name',  'Silvia Gallo'"
echo "put 'italians', '4', 'personal-data:city',  'Rome'"
echo "put 'italians', '4', 'professional-data:role',  'Engenharia Industrial Madeireira'"
echo "put 'italians', '4', 'professional-data:salary',  '16770'"
echo "put 'italians', '5', 'personal-data:name',  'Rosa Donati'"
echo "put 'italians', '5', 'personal-data:city',  'Palermo'"
echo "put 'italians', '5', 'professional-data:role',  'Mecatronica Industrial'"
echo "put 'italians', '5', 'professional-data:salary',  '7037'"
echo "put 'italians', '6', 'personal-data:name',  'Simone Lombardo'"
echo "put 'italians', '6', 'personal-data:city',  'Trieste'"
echo "put 'italians', '6', 'professional-data:role',  'Biotecnologia e Bioquimica'"
echo "put 'italians', '6', 'professional-data:salary',  '11395'"
echo "put 'italians', '7', 'personal-data:name',  'Barbara Ferretti'"
echo "put 'italians', '7', 'personal-data:city',  'Florence'"
echo "put 'italians', '7', 'professional-data:role',  'Libras'"
echo "put 'italians', '7', 'professional-data:salary',  '18627'"
echo "put 'italians', '8', 'personal-data:name',  'Simone Ferrara'"
echo "put 'italians', '8', 'personal-data:city',  'Milan'"
echo "put 'italians', '8', 'professional-data:role',  'Engenharia de Minas'"
echo "put 'italians', '8', 'professional-data:salary',  '8129'"
echo "put 'italians', '9', 'personal-data:name',  'Vincenzo Giordano'"
echo "put 'italians', '9', 'personal-data:city',  'Messina'"
echo "put 'italians', '9', 'professional-data:role',  'Marketing'"
echo "put 'italians', '9', 'professional-data:salary',  '9919'"
echo "put 'italians', '10', 'personal-data:name',  'Giovanna Caputo'"
echo "put 'italians', '10', 'personal-data:city',  'Milan'"
echo "put 'italians', '10', 'professional-data:role',  'Comunicacao Institucional'"
echo "put 'italians', '10', 'professional-data:salary',  '9470'"